# fly.toml app configuration file generated for gestion-escolar on 2024-06-27T22:30:23-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gestion-escolar'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
